server {
    server_name hubcontract.kz www.hubcontract.kz 46.247.43.225;

    root /var/www/hubcontract-react-full/build;
    index index.html;

    # PDF и файлы из /documents/ — скачивание напрямую
    location /documents/ {
        add_header Content-Disposition "attachment";
    }

    # SPA fallback для всех остальных маршрутов
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Логи
    access_log /var/log/nginx/hubcontract_access.log;
    error_log /var/log/nginx/hubcontract_error.log;

    # Запретить доступ к скрытым файлам
    location ~ /\. {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hubcontract.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hubcontract.kz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.hubcontract.kz) {
        return 301 https://$host$request_uri;
    }

    if ($host = hubcontract.kz) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name hubcontract.kz www.hubcontract.kz 46.247.43.225;
    return 404;
}
